<?php

namespace Coins\Admin\ACFFieldsManager;

class CoinACFFieldsManager
{
    public function boot(): void
    {
        add_action('acf/init', [$this, 'register']);
        add_action('graphql_register_types', [$this, 'registerGraphqlFields']);
    }

    public function registerGraphqlFields(): void
    {
        register_graphql_field('Coin', 'shortTitle', [
            'type'        => 'String',
            'description' => 'Оригінальна назва з сайту НБУ (з позначкою металу)',
            'resolve'     => fn($post) => get_post_meta($post->databaseId, 'short_title', true) ?: null,
        ]);
    }

    public function register(): void
    {
        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        acf_add_local_field_group([
            'key' => 'group_coin_fields',
            'title' => 'Coin',
            'fields' => $this->getFields(),
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'coins',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
        ]);
    }

    private function getFields(): array
    {
        return [
            [
                'key'                => 'field_coin_short_title',
                'label'              => 'Short title',
                'name'               => 'short_title',
                'type'               => 'text',
                'instructions'       => 'Коротка назва',
                'required'           => 0,
                'readonly'           => 0,
                'wrapper'            => ['width' => '100'],
                'show_in_graphql'    => 1,
                'graphql_field_name' => 'shortTitle',
            ],
            [
                'key' => 'field_coin_issue_date',
                'label' => 'Issue date',
                'name' => 'issue_date',
                'type' => 'date_picker',
                'instructions' => 'Дата введення в обіг.',
                'required' => 0,
                'display_format' => 'd.m.Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
                'wrapper' => ['width' => '33.33'],
            ],
            [
                'key' => 'field_coin_denomination',
                'label' => 'Denomination',
                'name' => 'coin_denomination',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_denomination',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_quality_tax',
                'label' => 'Quality',
                'name' => 'coin_quality',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_quality',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_material',
                'label' => 'Material',
                'name' => 'coin_material',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_material',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_series',
                'label' => 'Series',
                'name' => 'coin_series',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_series',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_edge_tax',
                'label' => 'Edge',
                'name' => 'coin_edge',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_edge',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_diameter_tax',
                'label' => 'Diameter',
                'name' => 'coin_diameter',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_diameter',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_mintage_declared_tax',
                'label' => 'Mintage (declared)',
                'name' => 'coin_mintage_declared',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_mintage_declared',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_mintage_actual_tax',
                'label' => 'Mintage (actual)',
                'name' => 'coin_mintage_actual',
                'type' => 'taxonomy',
                'taxonomy' => 'coin_mintage_actual',
                'field_type' => 'select',
                'allow_null' => 1,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'multiple' => 0,
                'wrapper' => ['width' => '50'],
            ],
            [
                'key'           => 'field_coin_type_tax',
                'label'         => 'Type',
                'name'          => 'coin_type',
                'type'          => 'taxonomy',
                'taxonomy'      => 'coin_type',
                'field_type'    => 'select',
                'allow_null'    => 1,
                'add_term'      => 0,
                'save_terms'    => 1,
                'load_terms'    => 1,
                'return_format' => 'id',
                'multiple'      => 0,
                'wrapper'       => ['width' => '50'],
            ],
            [
                'key'           => 'field_coin_color_tax',
                'label'         => 'Color',
                'name'          => 'coin_color',
                'type'          => 'taxonomy',
                'taxonomy'      => 'coin_color',
                'field_type'    => 'select',
                'allow_null'    => 1,
                'add_term'      => 0,
                'save_terms'    => 1,
                'load_terms'    => 1,
                'return_format' => 'id',
                'multiple'      => 0,
                'wrapper'       => ['width' => '50'],
            ],
            [
                'key'           => 'field_coin_packaging_tax',
                'label'         => 'Packaging',
                'name'          => 'coin_packaging',
                'type'          => 'taxonomy',
                'taxonomy'      => 'coin_packaging',
                'field_type'    => 'select',
                'allow_null'    => 1,
                'add_term'      => 0,
                'save_terms'    => 1,
                'load_terms'    => 1,
                'return_format' => 'id',
                'multiple'      => 0,
                'wrapper'       => ['width' => '50'],
            ],
            [
                'key' => 'field_coin_designers_artist',
                'label' => 'Художник',
                'name' => 'designers_artist',
                'type' => 'relationship',
                'instructions' => 'Художник (CPT Designers).',
                'required' => 0,
                'post_type' => ['designer'],
                'filters' => ['search'],
                'elements' => '',
                'min' => 0,
                'max' => 0,
                'return_format' => 'id',
            ],
            [
                'key' => 'field_coin_designers_designer',
                'label' => 'Дизайнер',
                'name' => 'designers_designer',
                'type' => 'relationship',
                'instructions' => 'Дизайнер (CPT Designers).',
                'required' => 0,
                'post_type' => ['designer'],
                'filters' => ['search'],
                'elements' => '',
                'min' => 0,
                'max' => 0,
                'return_format' => 'id',
            ],
            [
                'key' => 'field_coin_designers_adaptation',
                'label' => 'Адаптація дизайну',
                'name' => 'designers_adaptation',
                'type' => 'relationship',
                'instructions' => 'Адаптація дизайну (CPT Designers).',
                'required' => 0,
                'post_type' => ['designer'],
                'filters' => ['search'],
                'elements' => '',
                'min' => 0,
                'max' => 0,
                'return_format' => 'id',
            ],
            [
                'key' => 'field_coin_designers_sculptor',
                'label' => 'Скульптор',
                'name' => 'designers_sculptor',
                'type' => 'relationship',
                'instructions' => 'Скульптор (CPT Designers).',
                'required' => 0,
                'post_type' => ['designer'],
                'filters' => ['search'],
                'elements' => '',
                'min' => 0,
                'max' => 0,
                'return_format' => 'id',
            ],
            [
                'key' => 'field_coin_booklet_url',
                'label' => 'Booklet URL',
                'name' => 'booklet_url',
                'type' => 'url',
                'instructions' => 'Посилання на буклет (НБУ).',
                'required' => 0,
            ],
            [
                'key' => 'field_coin_description_html',
                'label' => 'Description (HTML)',
                'name' => 'description_html',
                'type' => 'wysiwyg',
                'instructions' => 'HTML-опис з НБУ (зберігаємо як є).',
                'required' => 0,
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ],
            [
                'key' => 'field_coin_images_gallery',
                'label' => 'Images gallery',
                'name' => 'images_gallery',
                'type' => 'gallery',
                'instructions' => 'Зображення монети (галерея).',
                'required' => 0,
                'return_format' => 'id',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'min' => 0,
                'max' => 0,
                'mime_types' => 'jpg,jpeg,png,webp',
            ],
        ];
    }
}